version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - flyway
    environment:
      DB_DSN: ${DB_DSN}
      BOT_KEY: ${BOT_KEY}
      MANAGER_CHAT_ID: ${MANAGER_CHAT_ID}
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - db

volumes:
  postgres_data: